### ISSUE TITLE
从红心生成歌单可能会遗漏最后几页歌曲

### ISSUE THREAD

**Issue by wpzdm** [fyl00/ExportXiamiList#2]
原因：267行计算页数使用勾选歌曲数除以每页歌曲数。这里没有考虑到由于版权问题下架的歌曲是不会勾选的，于是这样计算出来的页数可能会少。
解决：get_u_song方法其实已经可以判断是否该停止获取了（根据该页是否还有歌曲），所以get_list方法272、273行开始的循环不用以判断页数，直接从2开始往上循环，get_u_song返回false就停止循环，可以了。
PS：我是用的在线版本，发现问题才来看代码的。自己的老本子上就懒得搭环境跑了，对git也不熟……

**Comment by fyl00** [comment]
那个数不是勾选歌曲数，不过 get_u_song 有另外一个逻辑问题，你的这个解决办法更方便，已经改了。另外直接把在线版里代码传过来了，没用之前的那个版本了。https://github.com/fyl00/ExportXiamiList/commit/c2d8d5ea2cff7789c203d48d4476b90a96055b67
